version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            sudo pip install --upgrade pip
            sudo pip install -r ./requirements.txt
            py.test client/test/test_minimal.tavern.yaml -v